// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission06_bzp123.Models;

namespace mission06_bzp123.Migrations
{
    [DbContext(typeof(MovieEntryContex))]
    [Migration("20230221054308_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission06_bzp123.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Romantic Comedy"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Science Fiction"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Action"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Family"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Fantasy"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Thriller"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Musical"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Mystery"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "See Notes"
                        });
                });

            modelBuilder.Entity("mission06_bzp123.Models.NewMovieForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormID");

                    b.HasIndex("CategoryId");

                    b.ToTable("NewMovies");

                    b.HasData(
                        new
                        {
                            FormID = 1,
                            CategoryId = 10,
                            DirectorFirstName = "Phyllida",
                            DirectorLastName = "Lloyd",
                            Edited = false,
                            LentTo = "My parents",
                            Notes = "Fun Musical",
                            Rating = "PG-13",
                            Title = "Mamma Mia!",
                            Year = 2008
                        },
                        new
                        {
                            FormID = 2,
                            CategoryId = 2,
                            DirectorFirstName = "Phillip",
                            DirectorLastName = "Noyce",
                            Edited = false,
                            LentTo = "",
                            Notes = "Good Vibes",
                            Rating = "PG-13",
                            Title = "The Giver",
                            Year = 2014
                        },
                        new
                        {
                            FormID = 3,
                            CategoryId = 1,
                            DirectorFirstName = "Maclain",
                            DirectorLastName = "Nelson",
                            Edited = false,
                            LentTo = "My roommate",
                            Notes = "subversive",
                            Rating = "PG",
                            Title = "Once I Was Engaged",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("mission06_bzp123.Models.NewMovieForm", b =>
                {
                    b.HasOne("mission06_bzp123.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
