// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mission06_bzp123.Models;

namespace mission06_bzp123.Migrations
{
    [DbContext(typeof(MovieEntryContex))]
    partial class MovieEntryContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("mission06_bzp123.Models.NewMovieForm", b =>
                {
                    b.Property<int>("FormID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorFirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectorLastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("FormID");

                    b.ToTable("NewMovies");

                    b.HasData(
                        new
                        {
                            FormID = 1,
                            Category = "Musical/Romance",
                            DirectorFirstName = "Phyllida",
                            DirectorLastName = "Lloyd",
                            Edited = false,
                            LentTo = "My parents",
                            Notes = "Fun Musical",
                            Rating = "PG-13",
                            Title = "Mamma Mia!",
                            Year = 2008
                        },
                        new
                        {
                            FormID = 2,
                            Category = "Sci-fi",
                            DirectorFirstName = "Phillip",
                            DirectorLastName = "Noyce",
                            Edited = false,
                            LentTo = "",
                            Notes = "Good Vibes",
                            Rating = "PG-13",
                            Title = "The Giver",
                            Year = 2014
                        },
                        new
                        {
                            FormID = 3,
                            Category = "Comedy",
                            DirectorFirstName = "Maclain",
                            DirectorLastName = "Nelson",
                            Edited = false,
                            LentTo = "My roommate",
                            Notes = "subversive",
                            Rating = "PG",
                            Title = "Once I Was Engaged",
                            Year = 2021
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
